//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.24 at 01:57:35 PM BRT 
//


package br.org.abrasf.nfse;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Consulente" type="{http://www.abrasf.org.br/nfse.xsd}tcIdentificacaoConsulente"/>
 *         &lt;element name="NumeroNfse" type="{http://www.abrasf.org.br/nfse.xsd}tsNumeroNfse" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="PeriodoEmissao" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="DataInicial" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                     &lt;element name="DataFinal" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="PeriodoCompetencia" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="DataInicial" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                     &lt;element name="DataFinal" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *         &lt;element name="Prestador" type="{http://www.abrasf.org.br/nfse.xsd}tcIdentificacaoPrestador" minOccurs="0"/>
 *         &lt;element name="Tomador" type="{http://www.abrasf.org.br/nfse.xsd}tcIdentificacaoTomador" minOccurs="0"/>
 *         &lt;element name="Intermediario" type="{http://www.abrasf.org.br/nfse.xsd}tcIdentificacaoIntermediario" minOccurs="0"/>
 *         &lt;element name="Pagina" type="{http://www.abrasf.org.br/nfse.xsd}tsPagina"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "consulente",
    "numeroNfse",
    "periodoEmissao",
    "periodoCompetencia",
    "prestador",
    "tomador",
    "intermediario",
    "pagina"
})
@XmlRootElement(name = "ConsultarNfseServicoTomadoEnvio")
public class ConsultarNfseServicoTomadoEnvio {

    @XmlElement(name = "Consulente", required = true)
    protected TcIdentificacaoConsulente consulente;
    @XmlElement(name = "NumeroNfse")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numeroNfse;
    @XmlElement(name = "PeriodoEmissao")
    protected ConsultarNfseServicoTomadoEnvio.PeriodoEmissao periodoEmissao;
    @XmlElement(name = "PeriodoCompetencia")
    protected ConsultarNfseServicoTomadoEnvio.PeriodoCompetencia periodoCompetencia;
    @XmlElement(name = "Prestador")
    protected TcIdentificacaoPrestador prestador;
    @XmlElement(name = "Tomador")
    protected TcIdentificacaoTomador tomador;
    @XmlElement(name = "Intermediario")
    protected TcIdentificacaoIntermediario intermediario;
    @XmlElement(name = "Pagina")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected int pagina;

    /**
     * Gets the value of the consulente property.
     * 
     * @return
     *     possible object is
     *     {@link TcIdentificacaoConsulente }
     *     
     */
    public TcIdentificacaoConsulente getConsulente() {
        return consulente;
    }

    /**
     * Sets the value of the consulente property.
     * 
     * @param value
     *     allowed object is
     *     {@link TcIdentificacaoConsulente }
     *     
     */
    public void setConsulente(TcIdentificacaoConsulente value) {
        this.consulente = value;
    }

    /**
     * Gets the value of the numeroNfse property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumeroNfse() {
        return numeroNfse;
    }

    /**
     * Sets the value of the numeroNfse property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumeroNfse(BigInteger value) {
        this.numeroNfse = value;
    }

    /**
     * Gets the value of the periodoEmissao property.
     * 
     * @return
     *     possible object is
     *     {@link ConsultarNfseServicoTomadoEnvio.PeriodoEmissao }
     *     
     */
    public ConsultarNfseServicoTomadoEnvio.PeriodoEmissao getPeriodoEmissao() {
        return periodoEmissao;
    }

    /**
     * Sets the value of the periodoEmissao property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsultarNfseServicoTomadoEnvio.PeriodoEmissao }
     *     
     */
    public void setPeriodoEmissao(ConsultarNfseServicoTomadoEnvio.PeriodoEmissao value) {
        this.periodoEmissao = value;
    }

    /**
     * Gets the value of the periodoCompetencia property.
     * 
     * @return
     *     possible object is
     *     {@link ConsultarNfseServicoTomadoEnvio.PeriodoCompetencia }
     *     
     */
    public ConsultarNfseServicoTomadoEnvio.PeriodoCompetencia getPeriodoCompetencia() {
        return periodoCompetencia;
    }

    /**
     * Sets the value of the periodoCompetencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsultarNfseServicoTomadoEnvio.PeriodoCompetencia }
     *     
     */
    public void setPeriodoCompetencia(ConsultarNfseServicoTomadoEnvio.PeriodoCompetencia value) {
        this.periodoCompetencia = value;
    }

    /**
     * Gets the value of the prestador property.
     * 
     * @return
     *     possible object is
     *     {@link TcIdentificacaoPrestador }
     *     
     */
    public TcIdentificacaoPrestador getPrestador() {
        return prestador;
    }

    /**
     * Sets the value of the prestador property.
     * 
     * @param value
     *     allowed object is
     *     {@link TcIdentificacaoPrestador }
     *     
     */
    public void setPrestador(TcIdentificacaoPrestador value) {
        this.prestador = value;
    }

    /**
     * Gets the value of the tomador property.
     * 
     * @return
     *     possible object is
     *     {@link TcIdentificacaoTomador }
     *     
     */
    public TcIdentificacaoTomador getTomador() {
        return tomador;
    }

    /**
     * Sets the value of the tomador property.
     * 
     * @param value
     *     allowed object is
     *     {@link TcIdentificacaoTomador }
     *     
     */
    public void setTomador(TcIdentificacaoTomador value) {
        this.tomador = value;
    }

    /**
     * Gets the value of the intermediario property.
     * 
     * @return
     *     possible object is
     *     {@link TcIdentificacaoIntermediario }
     *     
     */
    public TcIdentificacaoIntermediario getIntermediario() {
        return intermediario;
    }

    /**
     * Sets the value of the intermediario property.
     * 
     * @param value
     *     allowed object is
     *     {@link TcIdentificacaoIntermediario }
     *     
     */
    public void setIntermediario(TcIdentificacaoIntermediario value) {
        this.intermediario = value;
    }

    /**
     * Gets the value of the pagina property.
     * 
     */
    public int getPagina() {
        return pagina;
    }

    /**
     * Sets the value of the pagina property.
     * 
     */
    public void setPagina(int value) {
        this.pagina = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DataInicial" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="DataFinal" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dataInicial",
        "dataFinal"
    })
    public static class PeriodoCompetencia {

        @XmlElement(name = "DataInicial", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar dataInicial;
        @XmlElement(name = "DataFinal", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar dataFinal;

        /**
         * Gets the value of the dataInicial property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDataInicial() {
            return dataInicial;
        }

        /**
         * Sets the value of the dataInicial property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDataInicial(XMLGregorianCalendar value) {
            this.dataInicial = value;
        }

        /**
         * Gets the value of the dataFinal property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDataFinal() {
            return dataFinal;
        }

        /**
         * Sets the value of the dataFinal property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDataFinal(XMLGregorianCalendar value) {
            this.dataFinal = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DataInicial" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="DataFinal" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dataInicial",
        "dataFinal"
    })
    public static class PeriodoEmissao {

        @XmlElement(name = "DataInicial", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar dataInicial;
        @XmlElement(name = "DataFinal", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar dataFinal;

        /**
         * Gets the value of the dataInicial property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDataInicial() {
            return dataInicial;
        }

        /**
         * Sets the value of the dataInicial property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDataInicial(XMLGregorianCalendar value) {
            this.dataInicial = value;
        }

        /**
         * Gets the value of the dataFinal property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDataFinal() {
            return dataFinal;
        }

        /**
         * Sets the value of the dataFinal property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDataFinal(XMLGregorianCalendar value) {
            this.dataFinal = value;
        }

    }

}
