//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.24 at 01:57:35 PM BRT 
//


package br.org.abrasf.nfse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.w3._2000._09.xmldsig_.SignatureType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SubstituicaoNfse">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Pedido" type="{http://www.abrasf.org.br/nfse.xsd}tcPedidoCancelamento"/>
 *                   &lt;element name="Rps" type="{http://www.abrasf.org.br/nfse.xsd}tcDeclaracaoPrestacaoServico"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="Id" type="{http://www.abrasf.org.br/nfse.xsd}tsIdTag" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}Signature" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "substituicaoNfse",
    "signature"
})
@XmlRootElement(name = "SubstituirNfseEnvio")
public class SubstituirNfseEnvio {

    @XmlElement(name = "SubstituicaoNfse", required = true)
    protected SubstituirNfseEnvio.SubstituicaoNfse substituicaoNfse;
    @XmlElement(name = "Signature", namespace = "http://www.w3.org/2000/09/xmldsig#")
    protected SignatureType signature;

    /**
     * Gets the value of the substituicaoNfse property.
     * 
     * @return
     *     possible object is
     *     {@link SubstituirNfseEnvio.SubstituicaoNfse }
     *     
     */
    public SubstituirNfseEnvio.SubstituicaoNfse getSubstituicaoNfse() {
        return substituicaoNfse;
    }

    /**
     * Sets the value of the substituicaoNfse property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubstituirNfseEnvio.SubstituicaoNfse }
     *     
     */
    public void setSubstituicaoNfse(SubstituirNfseEnvio.SubstituicaoNfse value) {
        this.substituicaoNfse = value;
    }

    /**
     * Gets the value of the signature property.
     * 
     * @return
     *     possible object is
     *     {@link SignatureType }
     *     
     */
    public SignatureType getSignature() {
        return signature;
    }

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureType }
     *     
     */
    public void setSignature(SignatureType value) {
        this.signature = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Pedido" type="{http://www.abrasf.org.br/nfse.xsd}tcPedidoCancelamento"/>
     *         &lt;element name="Rps" type="{http://www.abrasf.org.br/nfse.xsd}tcDeclaracaoPrestacaoServico"/>
     *       &lt;/sequence>
     *       &lt;attribute name="Id" type="{http://www.abrasf.org.br/nfse.xsd}tsIdTag" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "pedido",
        "rps"
    })
    public static class SubstituicaoNfse {

        @XmlElement(name = "Pedido", required = true)
        protected TcPedidoCancelamento pedido;
        @XmlElement(name = "Rps", required = true)
        protected TcDeclaracaoPrestacaoServico rps;
        @XmlAttribute(name = "Id")
        protected String id;

        /**
         * Gets the value of the pedido property.
         * 
         * @return
         *     possible object is
         *     {@link TcPedidoCancelamento }
         *     
         */
        public TcPedidoCancelamento getPedido() {
            return pedido;
        }

        /**
         * Sets the value of the pedido property.
         * 
         * @param value
         *     allowed object is
         *     {@link TcPedidoCancelamento }
         *     
         */
        public void setPedido(TcPedidoCancelamento value) {
            this.pedido = value;
        }

        /**
         * Gets the value of the rps property.
         * 
         * @return
         *     possible object is
         *     {@link TcDeclaracaoPrestacaoServico }
         *     
         */
        public TcDeclaracaoPrestacaoServico getRps() {
            return rps;
        }

        /**
         * Sets the value of the rps property.
         * 
         * @param value
         *     allowed object is
         *     {@link TcDeclaracaoPrestacaoServico }
         *     
         */
        public void setRps(TcDeclaracaoPrestacaoServico value) {
            this.rps = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

    }

}
