//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.24 at 01:57:35 PM BRT 
//


package br.org.abrasf.nfse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for tcInfDeclaracaoPrestacaoServico complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tcInfDeclaracaoPrestacaoServico">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Rps" type="{http://www.abrasf.org.br/nfse.xsd}tcInfRps" minOccurs="0"/>
 *         &lt;element name="Competencia" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Servico" type="{http://www.abrasf.org.br/nfse.xsd}tcDadosServico"/>
 *         &lt;element name="Prestador" type="{http://www.abrasf.org.br/nfse.xsd}tcIdentificacaoPrestador"/>
 *         &lt;element name="Tomador" type="{http://www.abrasf.org.br/nfse.xsd}tcDadosTomador" minOccurs="0"/>
 *         &lt;element name="Intermediario" type="{http://www.abrasf.org.br/nfse.xsd}tcDadosIntermediario" minOccurs="0"/>
 *         &lt;element name="ConstrucaoCivil" type="{http://www.abrasf.org.br/nfse.xsd}tcDadosConstrucaoCivil" minOccurs="0"/>
 *         &lt;element name="RegimeEspecialTributacao" type="{http://www.abrasf.org.br/nfse.xsd}tsRegimeEspecialTributacao" minOccurs="0"/>
 *         &lt;element name="OptanteSimplesNacional" type="{http://www.abrasf.org.br/nfse.xsd}tsSimNao"/>
 *         &lt;element name="IncentivoFiscal" type="{http://www.abrasf.org.br/nfse.xsd}tsSimNao"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Id" type="{http://www.abrasf.org.br/nfse.xsd}tsIdTag" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tcInfDeclaracaoPrestacaoServico", propOrder = {
    "rps",
    "competencia",
    "servico",
    "prestador",
    "tomador",
    "intermediario",
    "construcaoCivil",
    "regimeEspecialTributacao",
    "optanteSimplesNacional",
    "incentivoFiscal"
})
public class TcInfDeclaracaoPrestacaoServico {

    @XmlElement(name = "Rps")
    protected TcInfRps rps;
    @XmlElement(name = "Competencia", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar competencia;
    @XmlElement(name = "Servico", required = true)
    protected TcDadosServico servico;
    @XmlElement(name = "Prestador", required = true)
    protected TcIdentificacaoPrestador prestador;
    @XmlElement(name = "Tomador")
    protected TcDadosTomador tomador;
    @XmlElement(name = "Intermediario")
    protected TcDadosIntermediario intermediario;
    @XmlElement(name = "ConstrucaoCivil")
    protected TcDadosConstrucaoCivil construcaoCivil;
    @XmlElement(name = "RegimeEspecialTributacao")
    protected Byte regimeEspecialTributacao;
    @XmlElement(name = "OptanteSimplesNacional")
    protected byte optanteSimplesNacional;
    @XmlElement(name = "IncentivoFiscal")
    protected byte incentivoFiscal;
    @XmlAttribute(name = "Id")
    protected String id;

    /**
     * Gets the value of the rps property.
     * 
     * @return
     *     possible object is
     *     {@link TcInfRps }
     *     
     */
    public TcInfRps getRps() {
        return rps;
    }

    /**
     * Sets the value of the rps property.
     * 
     * @param value
     *     allowed object is
     *     {@link TcInfRps }
     *     
     */
    public void setRps(TcInfRps value) {
        this.rps = value;
    }

    /**
     * Gets the value of the competencia property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCompetencia() {
        return competencia;
    }

    /**
     * Sets the value of the competencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCompetencia(XMLGregorianCalendar value) {
        this.competencia = value;
    }

    /**
     * Gets the value of the servico property.
     * 
     * @return
     *     possible object is
     *     {@link TcDadosServico }
     *     
     */
    public TcDadosServico getServico() {
        return servico;
    }

    /**
     * Sets the value of the servico property.
     * 
     * @param value
     *     allowed object is
     *     {@link TcDadosServico }
     *     
     */
    public void setServico(TcDadosServico value) {
        this.servico = value;
    }

    /**
     * Gets the value of the prestador property.
     * 
     * @return
     *     possible object is
     *     {@link TcIdentificacaoPrestador }
     *     
     */
    public TcIdentificacaoPrestador getPrestador() {
        return prestador;
    }

    /**
     * Sets the value of the prestador property.
     * 
     * @param value
     *     allowed object is
     *     {@link TcIdentificacaoPrestador }
     *     
     */
    public void setPrestador(TcIdentificacaoPrestador value) {
        this.prestador = value;
    }

    /**
     * Gets the value of the tomador property.
     * 
     * @return
     *     possible object is
     *     {@link TcDadosTomador }
     *     
     */
    public TcDadosTomador getTomador() {
        return tomador;
    }

    /**
     * Sets the value of the tomador property.
     * 
     * @param value
     *     allowed object is
     *     {@link TcDadosTomador }
     *     
     */
    public void setTomador(TcDadosTomador value) {
        this.tomador = value;
    }

    /**
     * Gets the value of the intermediario property.
     * 
     * @return
     *     possible object is
     *     {@link TcDadosIntermediario }
     *     
     */
    public TcDadosIntermediario getIntermediario() {
        return intermediario;
    }

    /**
     * Sets the value of the intermediario property.
     * 
     * @param value
     *     allowed object is
     *     {@link TcDadosIntermediario }
     *     
     */
    public void setIntermediario(TcDadosIntermediario value) {
        this.intermediario = value;
    }

    /**
     * Gets the value of the construcaoCivil property.
     * 
     * @return
     *     possible object is
     *     {@link TcDadosConstrucaoCivil }
     *     
     */
    public TcDadosConstrucaoCivil getConstrucaoCivil() {
        return construcaoCivil;
    }

    /**
     * Sets the value of the construcaoCivil property.
     * 
     * @param value
     *     allowed object is
     *     {@link TcDadosConstrucaoCivil }
     *     
     */
    public void setConstrucaoCivil(TcDadosConstrucaoCivil value) {
        this.construcaoCivil = value;
    }

    /**
     * Gets the value of the regimeEspecialTributacao property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getRegimeEspecialTributacao() {
        return regimeEspecialTributacao;
    }

    /**
     * Sets the value of the regimeEspecialTributacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setRegimeEspecialTributacao(Byte value) {
        this.regimeEspecialTributacao = value;
    }

    /**
     * Gets the value of the optanteSimplesNacional property.
     * 
     */
    public byte getOptanteSimplesNacional() {
        return optanteSimplesNacional;
    }

    /**
     * Sets the value of the optanteSimplesNacional property.
     * 
     */
    public void setOptanteSimplesNacional(byte value) {
        this.optanteSimplesNacional = value;
    }

    /**
     * Gets the value of the incentivoFiscal property.
     * 
     */
    public byte getIncentivoFiscal() {
        return incentivoFiscal;
    }

    /**
     * Sets the value of the incentivoFiscal property.
     * 
     */
    public void setIncentivoFiscal(byte value) {
        this.incentivoFiscal = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
