//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.24 at 01:57:35 PM BRT 
//


package br.org.abrasf.nfse;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tcValoresDeclaracaoServico complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tcValoresDeclaracaoServico">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ValorServicos" type="{http://www.abrasf.org.br/nfse.xsd}tsValor"/>
 *         &lt;element name="ValorDeducoes" type="{http://www.abrasf.org.br/nfse.xsd}tsValor" minOccurs="0"/>
 *         &lt;element name="ValorPis" type="{http://www.abrasf.org.br/nfse.xsd}tsValor" minOccurs="0"/>
 *         &lt;element name="ValorCofins" type="{http://www.abrasf.org.br/nfse.xsd}tsValor" minOccurs="0"/>
 *         &lt;element name="ValorInss" type="{http://www.abrasf.org.br/nfse.xsd}tsValor" minOccurs="0"/>
 *         &lt;element name="ValorIr" type="{http://www.abrasf.org.br/nfse.xsd}tsValor" minOccurs="0"/>
 *         &lt;element name="ValorCsll" type="{http://www.abrasf.org.br/nfse.xsd}tsValor" minOccurs="0"/>
 *         &lt;element name="OutrasRetencoes" type="{http://www.abrasf.org.br/nfse.xsd}tsValor" minOccurs="0"/>
 *         &lt;element name="ValorIss" type="{http://www.abrasf.org.br/nfse.xsd}tsValor" minOccurs="0"/>
 *         &lt;element name="Aliquota" type="{http://www.abrasf.org.br/nfse.xsd}tsAliquota" minOccurs="0"/>
 *         &lt;element name="DescontoIncondicionado" type="{http://www.abrasf.org.br/nfse.xsd}tsValor" minOccurs="0"/>
 *         &lt;element name="DescontoCondicionado" type="{http://www.abrasf.org.br/nfse.xsd}tsValor" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tcValoresDeclaracaoServico", propOrder = {
    "valorServicos",
    "valorDeducoes",
    "valorPis",
    "valorCofins",
    "valorInss",
    "valorIr",
    "valorCsll",
    "outrasRetencoes",
    "valorIss",
    "aliquota",
    "descontoIncondicionado",
    "descontoCondicionado"
})
public class TcValoresDeclaracaoServico {

    @XmlElement(name = "ValorServicos", required = true)
    protected BigDecimal valorServicos;
    @XmlElement(name = "ValorDeducoes")
    protected BigDecimal valorDeducoes;
    @XmlElement(name = "ValorPis")
    protected BigDecimal valorPis;
    @XmlElement(name = "ValorCofins")
    protected BigDecimal valorCofins;
    @XmlElement(name = "ValorInss")
    protected BigDecimal valorInss;
    @XmlElement(name = "ValorIr")
    protected BigDecimal valorIr;
    @XmlElement(name = "ValorCsll")
    protected BigDecimal valorCsll;
    @XmlElement(name = "OutrasRetencoes")
    protected BigDecimal outrasRetencoes;
    @XmlElement(name = "ValorIss")
    protected BigDecimal valorIss;
    @XmlElement(name = "Aliquota")
    protected BigDecimal aliquota;
    @XmlElement(name = "DescontoIncondicionado")
    protected BigDecimal descontoIncondicionado;
    @XmlElement(name = "DescontoCondicionado")
    protected BigDecimal descontoCondicionado;

    /**
     * Gets the value of the valorServicos property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorServicos() {
        return valorServicos;
    }

    /**
     * Sets the value of the valorServicos property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorServicos(BigDecimal value) {
        this.valorServicos = value;
    }

    /**
     * Gets the value of the valorDeducoes property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorDeducoes() {
        return valorDeducoes;
    }

    /**
     * Sets the value of the valorDeducoes property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorDeducoes(BigDecimal value) {
        this.valorDeducoes = value;
    }

    /**
     * Gets the value of the valorPis property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorPis() {
        return valorPis;
    }

    /**
     * Sets the value of the valorPis property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorPis(BigDecimal value) {
        this.valorPis = value;
    }

    /**
     * Gets the value of the valorCofins property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorCofins() {
        return valorCofins;
    }

    /**
     * Sets the value of the valorCofins property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorCofins(BigDecimal value) {
        this.valorCofins = value;
    }

    /**
     * Gets the value of the valorInss property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorInss() {
        return valorInss;
    }

    /**
     * Sets the value of the valorInss property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorInss(BigDecimal value) {
        this.valorInss = value;
    }

    /**
     * Gets the value of the valorIr property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorIr() {
        return valorIr;
    }

    /**
     * Sets the value of the valorIr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorIr(BigDecimal value) {
        this.valorIr = value;
    }

    /**
     * Gets the value of the valorCsll property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorCsll() {
        return valorCsll;
    }

    /**
     * Sets the value of the valorCsll property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorCsll(BigDecimal value) {
        this.valorCsll = value;
    }

    /**
     * Gets the value of the outrasRetencoes property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOutrasRetencoes() {
        return outrasRetencoes;
    }

    /**
     * Sets the value of the outrasRetencoes property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOutrasRetencoes(BigDecimal value) {
        this.outrasRetencoes = value;
    }

    /**
     * Gets the value of the valorIss property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorIss() {
        return valorIss;
    }

    /**
     * Sets the value of the valorIss property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorIss(BigDecimal value) {
        this.valorIss = value;
    }

    /**
     * Gets the value of the aliquota property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAliquota() {
        return aliquota;
    }

    /**
     * Sets the value of the aliquota property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAliquota(BigDecimal value) {
        this.aliquota = value;
    }

    /**
     * Gets the value of the descontoIncondicionado property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDescontoIncondicionado() {
        return descontoIncondicionado;
    }

    /**
     * Sets the value of the descontoIncondicionado property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDescontoIncondicionado(BigDecimal value) {
        this.descontoIncondicionado = value;
    }

    /**
     * Gets the value of the descontoCondicionado property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDescontoCondicionado() {
        return descontoCondicionado;
    }

    /**
     * Sets the value of the descontoCondicionado property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDescontoCondicionado(BigDecimal value) {
        this.descontoCondicionado = value;
    }

}
